"""Cedar policy builder and validator.

Generates Cedar policy files that AgentCore evaluates at the Gateway level
to control which agents can invoke which tools in which execution modes.

Cedar policies are defined as Python structures, serialized to .cedar format,
and deployed via CDK.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

logger = logging.getLogger(__name__)


class PolicyEffect(str, Enum):
    """Cedar policy effect."""

    PERMIT = "permit"
    FORBID = "forbid"


class PolicyAction(str, Enum):
    """Actions controlled by Cedar policies."""

    INVOKE_TOOL = "invoke_tool"
    READ_MEMORY = "read_memory"
    WRITE_MEMORY = "write_memory"


@dataclass
class CedarPolicy:
    """A single Cedar policy rule.

    Attributes:
        policy_id: Unique identifier for the policy.
        effect: PERMIT or FORBID.
        description: Human-readable description.
        principal: Agent or AgentGroup (e.g., 'Agent::"my_agent"').
        action: Action being controlled.
        resource: Tool or ToolGroup (e.g., 'Tool::"my-mcp::my_tool"').
        conditions: Optional "when" conditions (Cedar expression strings).
    """

    policy_id: str
    effect: PolicyEffect
    description: str
    principal: str
    action: PolicyAction
    resource: str
    conditions: list[str] = field(default_factory=list)

    def to_cedar(self) -> str:
        """Serialize this policy to Cedar format.

        Returns:
            Cedar policy string.
        """
        lines = [f"// {self.description}"]

        principal_clause = f"principal == {self.principal}"
        action_clause = f'action == Action::"{self.action.value}"'
        resource_clause = f"resource == {self.resource}"

        # Handle "in" syntax for groups
        if "in " in self.principal:
            principal_clause = f"principal {self.principal}"
        if "in " in self.resource:
            resource_clause = f"resource {self.resource}"

        lines.append(f"{self.effect.value}(")
        lines.append(f"    {principal_clause},")
        lines.append(f"    {action_clause},")
        lines.append(f"    {resource_clause}")
        lines.append(")")

        if self.conditions:
            conditions_str = " && ".join(self.conditions)
            lines[-1] = lines[-1].rstrip(")")
            lines.append(f"when {{ {conditions_str} }};")
        else:
            lines[-1] += ";"

        return "\n".join(lines)


class CedarPolicyBuilder:
    """Builds and serializes Cedar policy sets.

    Usage:
        builder = CedarPolicyBuilder()
        builder.add_policy(policy)
        cedar_text = builder.build()
        builder.write_to_file("cedar/policies.cedar")
    """

    def __init__(self) -> None:
        self.policies: list[CedarPolicy] = []

    def add_policy(self, policy: CedarPolicy) -> CedarPolicyBuilder:
        """Add a policy to the builder.

        Args:
            policy: CedarPolicy to add.

        Returns:
            self for chaining.
        """
        self.policies.append(policy)
        return self

    def load_policies_from_file(self, path: str) -> CedarPolicyBuilder:
        """Load policies from a YAML file and add them to the builder.

        Args:
            path: Path to YAML file with policy definitions.

        Returns:
            self for chaining.
        """
        import yaml  # type: ignore[import-untyped]

        with open(path) as f:
            data = yaml.safe_load(f)

        for entry in data.get("policies", []):
            policy = CedarPolicy(
                policy_id=entry["policy_id"],
                effect=PolicyEffect(entry["effect"]),
                description=entry.get("description", ""),
                principal=entry["principal"],
                action=PolicyAction(entry["action"]),
                resource=entry["resource"],
                conditions=entry.get("conditions", []),
            )
            self.policies.append(policy)

        logger.info("Loaded %d policies from %s", len(data.get("policies", [])), path)
        return self

    def build(self) -> str:
        """Serialize all policies to Cedar format.

        Returns:
            Complete Cedar policy file content.
        """
        header = (
            "// Cedar Policies -- AgentCore Tool Access Control\n"
            "// Generated by agent_core.policy.cedar_policies\n"
            "// DO NOT EDIT MANUALLY -- regenerate via CedarPolicyBuilder\n"
            "\n"
        )

        policy_texts = []
        for policy in self.policies:
            policy_texts.append(policy.to_cedar())

        return header + "\n\n".join(policy_texts) + "\n"

    def write_to_file(self, path: str) -> None:
        """Write policies to a .cedar file.

        Args:
            path: File path for the Cedar policy file.
        """
        content = self.build()
        with open(path, "w") as f:
            f.write(content)
        logger.info("Wrote %d Cedar policies to %s", len(self.policies), path)


# ─── Cedar Entity Schema ────────────────────────────────────────────

CEDAR_SCHEMA = {
    "AgentCore": {
        "entityTypes": {
            "Agent": {
                "memberOfTypes": ["AgentGroup"],
                "shape": {
                    "type": "Record",
                    "attributes": {
                        "agent_id": {"type": "String"},
                        "execution_mode": {"type": "String"},
                    },
                },
            },
            "AgentGroup": {
                "shape": {
                    "type": "Record",
                    "attributes": {
                        "group_id": {"type": "String"},
                    },
                },
            },
            "Tool": {
                "memberOfTypes": ["ToolGroup"],
                "shape": {
                    "type": "Record",
                    "attributes": {
                        "tool_name": {"type": "String"},
                        "target": {"type": "String"},
                        "session_id": {"type": "String"},
                    },
                },
            },
            "ToolGroup": {
                "shape": {
                    "type": "Record",
                    "attributes": {
                        "group_id": {"type": "String"},
                    },
                },
            },
        },
        "actions": {
            "invoke_tool": {
                "appliesTo": {
                    "principalTypes": ["Agent", "AgentGroup"],
                    "resourceTypes": ["Tool", "ToolGroup"],
                    "context": {
                        "type": "Record",
                        "attributes": {
                            "execution_mode": {"type": "String"},
                            "session_id": {"type": "String"},
                        },
                    },
                },
            },
            "read_memory": {
                "appliesTo": {
                    "principalTypes": ["Agent"],
                    "resourceTypes": ["Tool"],
                    "context": {
                        "type": "Record",
                        "attributes": {
                            "session_id": {"type": "String"},
                        },
                    },
                },
            },
            "write_memory": {
                "appliesTo": {
                    "principalTypes": ["Agent"],
                    "resourceTypes": ["Tool"],
                    "context": {
                        "type": "Record",
                        "attributes": {
                            "session_id": {"type": "String"},
                        },
                    },
                },
            },
        },
    },
}


def validate_policy_set(policies: list[CedarPolicy]) -> list[str]:
    """Validate a set of Cedar policies for consistency.

    Checks:
    - No duplicate policy IDs
    - No conflicting PERMIT/FORBID for same principal+action+resource

    Args:
        policies: List of CedarPolicy objects to validate.

    Returns:
        List of warning/error messages (empty if all valid).
    """
    errors: list[str] = []

    # Check duplicate IDs
    ids = [p.policy_id for p in policies]
    duplicates = [pid for pid in ids if ids.count(pid) > 1]
    if duplicates:
        errors.append(f"Duplicate policy IDs: {set(duplicates)}")

    return errors


def generate_cedar_files(
    output_dir: str,
    policy_file: str | None = None,
) -> None:
    """Generate Cedar policy and schema files.

    Args:
        output_dir: Directory to write files to.
        policy_file: Optional YAML file with policy definitions.
                     If not provided, generates only the schema.
    """
    import json
    import os

    os.makedirs(output_dir, exist_ok=True)

    builder = CedarPolicyBuilder()
    if policy_file:
        builder.load_policies_from_file(policy_file)

    if builder.policies:
        builder.write_to_file(os.path.join(output_dir, "policies.cedar"))

    schema_path = os.path.join(output_dir, "schema.cedarschema")
    with open(schema_path, "w") as f:
        json.dump(CEDAR_SCHEMA, f, indent=2)
    logger.info("Wrote Cedar schema to %s", schema_path)
